image: mcr.microsoft.com/dotnet/core/sdk:latest

stages:
    - deploy

pages:
  stage: deploy
  script:
    - "dotnet build ./base_vb/base_vb.sln"
    - "dotnet ./base_vb/bin/Debug/netcoreapp3.1/vbb.dll g"
    - mv docs public
  artifacts:
    paths:
      - public
  only:
    - master
    
